/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Kyra Balliram
 */
public class AssidLevelThree extends javax.swing.JFrame {

    /**
     * Creates new form AssidLevelThree
     */
    public AssidLevelThree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        L3Card2 = new javax.swing.JButton();
        L3Card8 = new javax.swing.JButton();
        L3Card3 = new javax.swing.JButton();
        L3Card4 = new javax.swing.JButton();
        L3Card5 = new javax.swing.JButton();
        L3Card10 = new javax.swing.JButton();
        L2Card7 = new javax.swing.JButton();
        L3Card9 = new javax.swing.JButton();
        L3Card1 = new javax.swing.JButton();
        L3Card6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        L3Scoretxt = new javax.swing.JLabel();
        L3LevelTxt = new javax.swing.JLabel();
        L3CasinoImage = new javax.swing.JLabel();

        jButton11.setText("Start");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L3Card2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card2ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 66, 92));

        L3Card8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card8ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 66, 92));

        L3Card3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card3ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 66, 92));

        L3Card4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card4ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 66, 92));

        L3Card5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card5ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 66, 92));

        L3Card10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card10ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 66, 92));

        L2Card7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card7ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 66, 92));

        L3Card9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card9ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 66, 92));

        L3Card1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card1ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 66, 92));

        L3Card6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3Card6ActionPerformed(evt);
            }
        });
        getContentPane().add(L3Card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 66, 92));

        jButton12.setText("Start");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 73, -1));

        jButton13.setText("Return Home");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        L3Scoretxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        L3Scoretxt.setForeground(new java.awt.Color(255, 255, 255));
        L3Scoretxt.setText("Score:");
        getContentPane().add(L3Scoretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 86, -1));

        L3LevelTxt.setBackground(new java.awt.Color(255, 102, 102));
        L3LevelTxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        L3LevelTxt.setForeground(new java.awt.Color(255, 255, 255));
        L3LevelTxt.setText("Level:");
        getContentPane().add(L3LevelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, -1));

        L3CasinoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casino.jpeg"))); // NOI18N
        getContentPane().add(L3CasinoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L3Card2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card2ActionPerformed

    private void L3Card8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card8ActionPerformed

    private void L3Card3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card3ActionPerformed

    private void L3Card4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card4ActionPerformed

    private void L3Card5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card5ActionPerformed

    private void L3Card10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card10ActionPerformed

    private void L2Card7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card7ActionPerformed

    private void L3Card9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card9ActionPerformed

    private void L3Card1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card1ActionPerformed

    private void L3Card6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3Card6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L3Card6ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_jButton13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssidLevelThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssidLevelThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssidLevelThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssidLevelThree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssidLevelThree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton L2Card7;
    private javax.swing.JButton L3Card1;
    private javax.swing.JButton L3Card10;
    private javax.swing.JButton L3Card2;
    private javax.swing.JButton L3Card3;
    private javax.swing.JButton L3Card4;
    private javax.swing.JButton L3Card5;
    private javax.swing.JButton L3Card6;
    private javax.swing.JButton L3Card8;
    private javax.swing.JButton L3Card9;
    private javax.swing.JLabel L3CasinoImage;
    private javax.swing.JLabel L3LevelTxt;
    private javax.swing.JLabel L3Scoretxt;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    // End of variables declaration//GEN-END:variables
}
