/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Kyra Balliram
 */
public class Assiduous extends javax.swing.JFrame {

    /**
     * Creates new form Assiduous
     */
    public Assiduous() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new javax.swing.JButton();
        card2 = new javax.swing.JButton();
        card5 = new javax.swing.JButton();
        card4 = new javax.swing.JButton();
        card6 = new javax.swing.JButton();
        card3 = new javax.swing.JButton();
        LevelTxt = new javax.swing.JLabel();
        startB = new javax.swing.JButton();
        HTPA = new javax.swing.JButton();
        ScoreTxt = new javax.swing.JLabel();
        ReturnB1 = new javax.swing.JButton();
        CasinoImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setBackground(new java.awt.Color(44, 62, 80));
        card1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card1ActionPerformed(evt);
            }
        });
        getContentPane().add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 66, 92));

        card2.setBackground(new java.awt.Color(44, 62, 80));
        getContentPane().add(card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 66, 92));

        card5.setBackground(new java.awt.Color(44, 62, 80));
        getContentPane().add(card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 66, 92));

        card4.setBackground(new java.awt.Color(44, 62, 80));
        getContentPane().add(card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 66, 92));

        card6.setBackground(new java.awt.Color(44, 62, 80));
        getContentPane().add(card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 66, 92));

        card3.setBackground(new java.awt.Color(44, 62, 80));
        getContentPane().add(card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 66, 92));

        LevelTxt.setBackground(new java.awt.Color(255, 102, 102));
        LevelTxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LevelTxt.setForeground(new java.awt.Color(255, 255, 255));
        LevelTxt.setText("Level:");
        getContentPane().add(LevelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 80, -1));

        startB.setText("Start");
        getContentPane().add(startB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 73, -1));

        HTPA.setText("How to play");
        HTPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HTPAMouseClicked(evt);
            }
        });
        getContentPane().add(HTPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, -1));

        ScoreTxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ScoreTxt.setForeground(new java.awt.Color(255, 255, 255));
        ScoreTxt.setText("Score:");
        getContentPane().add(ScoreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 86, -1));

        ReturnB1.setText("Return Home");
        ReturnB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnB1MouseClicked(evt);
            }
        });
        getContentPane().add(ReturnB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        CasinoImage.setBackground(new java.awt.Color(255, 255, 102));
        CasinoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casino.jpeg"))); // NOI18N
        CasinoImage.setText("jLabel3");
        getContentPane().add(CasinoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 590, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void card1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card1ActionPerformed

    private void HTPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HTPAMouseClicked

        // TODO add your handling code here:
        dispose(); 
        new AssiduousInfo().setVisible(true);
        
    }//GEN-LAST:event_HTPAMouseClicked

    private void ReturnB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnB1MouseClicked

        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_ReturnB1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assiduous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assiduous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assiduous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assiduous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assiduous().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CasinoImage;
    private javax.swing.JButton HTPA;
    private javax.swing.JLabel LevelTxt;
    private javax.swing.JButton ReturnB1;
    private javax.swing.JLabel ScoreTxt;
    private javax.swing.JButton card1;
    private javax.swing.JButton card2;
    private javax.swing.JButton card3;
    private javax.swing.JButton card4;
    private javax.swing.JButton card5;
    private javax.swing.JButton card6;
    private javax.swing.JButton startB;
    // End of variables declaration//GEN-END:variables
}
