/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Kyra Balliram
 */
public class AssidLevelTwo extends javax.swing.JFrame {

    /**
     * Creates new form AssidLevelTwo
     */
    public AssidLevelTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L2Card8 = new javax.swing.JButton();
        L2Card1 = new javax.swing.JButton();
        L2Card5 = new javax.swing.JButton();
        L2Card6 = new javax.swing.JButton();
        L2Card2 = new javax.swing.JButton();
        L2Card3 = new javax.swing.JButton();
        L2Card7 = new javax.swing.JButton();
        L2Card4 = new javax.swing.JButton();
        L2StartB = new javax.swing.JButton();
        L2levelTxt = new javax.swing.JLabel();
        L2ScoreTxt = new javax.swing.JLabel();
        ReturnB1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L2Card8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card8ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 66, 92));

        L2Card1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card1ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 66, 92));

        L2Card5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card5ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 66, 92));

        L2Card6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card6ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 66, 92));

        L2Card2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card2ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 66, 92));

        L2Card3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card3ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 66, 92));

        L2Card7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card7ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 66, 92));

        L2Card4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2Card4ActionPerformed(evt);
            }
        });
        getContentPane().add(L2Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 66, 92));

        L2StartB.setText("Start");
        getContentPane().add(L2StartB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 73, -1));

        L2levelTxt.setBackground(new java.awt.Color(255, 102, 102));
        L2levelTxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        L2levelTxt.setForeground(new java.awt.Color(255, 255, 255));
        L2levelTxt.setText("Level:");
        getContentPane().add(L2levelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 80, -1));

        L2ScoreTxt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        L2ScoreTxt.setForeground(new java.awt.Color(255, 255, 255));
        L2ScoreTxt.setText("Score:");
        getContentPane().add(L2ScoreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 86, -1));

        ReturnB1.setText("Return Home");
        ReturnB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnB1MouseClicked(evt);
            }
        });
        getContentPane().add(ReturnB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casino.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void L2Card8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card8ActionPerformed

    private void L2Card1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card1ActionPerformed

    private void L2Card5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card5ActionPerformed

    private void L2Card6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card6ActionPerformed

    private void L2Card2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card2ActionPerformed

    private void L2Card3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card3ActionPerformed

    private void L2Card7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card7ActionPerformed

    private void L2Card4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2Card4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L2Card4ActionPerformed

    private void ReturnB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnB1MouseClicked
        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_ReturnB1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssidLevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssidLevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssidLevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssidLevelTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssidLevelTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton L2Card1;
    private javax.swing.JButton L2Card2;
    private javax.swing.JButton L2Card3;
    private javax.swing.JButton L2Card4;
    private javax.swing.JButton L2Card5;
    private javax.swing.JButton L2Card6;
    private javax.swing.JButton L2Card7;
    private javax.swing.JButton L2Card8;
    private javax.swing.JLabel L2ScoreTxt;
    private javax.swing.JButton L2StartB;
    private javax.swing.JLabel L2levelTxt;
    private javax.swing.JButton ReturnB1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
