/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.dateManagement;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Kyra Balliram
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    dateManagement dn;

    public HomeScreen() {
        initComponents();
        dn = new dateManagement();
        dateTxtArea.setText(dn.getDate());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        DailyMoodB = new javax.swing.JButton();
        CoursesB = new javax.swing.JButton();
        MoodJournalB = new javax.swing.JButton();
        MentalState = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dateTxtArea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 198, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DailyMoodB.setText("Daily mood");
        DailyMoodB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyMoodBActionPerformed(evt);
            }
        });
        jPanel1.add(DailyMoodB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));

        CoursesB.setText("Courses");
        CoursesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesBActionPerformed(evt);
            }
        });
        jPanel1.add(CoursesB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 30));

        MoodJournalB.setText("Mood Journal");
        MoodJournalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoodJournalBActionPerformed(evt);
            }
        });
        jPanel1.add(MoodJournalB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, 30));

        MentalState.setText("Mental State");
        MentalState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentalStateActionPerformed(evt);
            }
        });
        jPanel1.add(MentalState, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, 30));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Welcome to  Celestite");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 224, 41));

        jPanel2.setBackground(new java.awt.Color(36, 37, 42));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 220, 330));

        dateTxtArea.setEditable(false);
        jPanel1.add(dateTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoodJournalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodJournalBActionPerformed
        // TODO add your handling code here:
        dispose();
        new Journal().setVisible(true);
    }//GEN-LAST:event_MoodJournalBActionPerformed

    private void DailyMoodBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyMoodBActionPerformed
        dispose();
        new AddMood().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_DailyMoodBActionPerformed

    private void CoursesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesBActionPerformed
        // TODO add your handling code here:
        dispose();
        new Courses().setVisible(true);
    }//GEN-LAST:event_CoursesBActionPerformed

    private void MentalStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentalStateActionPerformed
        // TODO add your handling code here:
        dispose();
        new MentalState().setVisible(true);
    }//GEN-LAST:event_MentalStateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CoursesB;
    private javax.swing.JButton DailyMoodB;
    private javax.swing.JButton MentalState;
    private javax.swing.JButton MoodJournalB;
    private javax.swing.JTextField dateTxtArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
