/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.MoodManagement;
import Backend.StateQuiz;
import Backend.dateManagement;

/**
 *
 * @author Kyra Balliram
 */
public class Journal extends javax.swing.JFrame {

    /**
     * Creates new form Journal
     */
    StateQuiz sm;
    MoodManagement mm;
    dateManagement dn;

    public Journal() {
        initComponents();
        dn = new dateManagement();
        mm = new MoodManagement();
        sm = new StateQuiz();
        dateTxtArea.setText(dn.getDate());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OverallMoodB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EmotionB = new javax.swing.JButton();
        MentalStateB = new javax.swing.JButton();
        dateTxtArea = new javax.swing.JTextField();
        StatsTxtArea = new javax.swing.JTextField();
        BackB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(104, 195, 163));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverallMoodB.setText("View Overall Mood");
        OverallMoodB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverallMoodBActionPerformed(evt);
            }
        });
        jPanel1.add(OverallMoodB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 30));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Mood Journal:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 34));

        EmotionB.setText("View Emotions of today");
        EmotionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmotionBActionPerformed(evt);
            }
        });
        jPanel1.add(EmotionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 30));

        MentalStateB.setText("View Mental State");
        MentalStateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentalStateBActionPerformed(evt);
            }
        });
        jPanel1.add(MentalStateB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 30));

        dateTxtArea.setEditable(false);
        dateTxtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtAreaActionPerformed(evt);
            }
        });
        jPanel1.add(dateTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, 30));

        StatsTxtArea.setEditable(false);
        jPanel1.add(StatsTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 190, 220));

        BackB.setText("Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });
        jPanel1.add(BackB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateTxtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtAreaActionPerformed

    private void OverallMoodBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverallMoodBActionPerformed
        // TODO add your handling code here:
        StatsTxtArea.setText("");
        StatsTxtArea.setText("Overall Mood:" + mm.getOverallMood()+ "\n");


    }//GEN-LAST:event_OverallMoodBActionPerformed

    private void EmotionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmotionBActionPerformed
        // TODO add your handling code here:
        StatsTxtArea.setText("");
        StatsTxtArea.setText( mm.getEmotion()+ "\n");


    }//GEN-LAST:event_EmotionBActionPerformed

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_BackBActionPerformed

    private void MentalStateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentalStateBActionPerformed
        // TODO add your handling code here:
        StatsTxtArea.setText("");//resets text area so that previous text is removed
        StatsTxtArea.setText("Results:" + sm.getResult());

    }//GEN-LAST:event_MentalStateBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Journal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Journal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackB;
    private javax.swing.JButton EmotionB;
    private javax.swing.JButton MentalStateB;
    private javax.swing.JButton OverallMoodB;
    private javax.swing.JTextField StatsTxtArea;
    private javax.swing.JTextField dateTxtArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
