/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Backend.StateQuiz;

/**
 *
 * @author Kyra Balliram
 */
public class QuestionResullts extends javax.swing.JFrame {

    /**
     * Creates new form QuestionResullts
     */
    public static int totalScore;

    public QuestionResullts() {
        initComponents();

        totalScore = StateQuiz.score(StateQuiz.choice1, StateQuiz.choice2, StateQuiz.choice3, StateQuiz.choice4, StateQuiz.choice5, StateQuiz.choice6, StateQuiz.choice7);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTxtArea = new javax.swing.JTextArea();
        ExitB = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        resultB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 190, 88));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultTxtArea.setEditable(false);
        resultTxtArea.setColumns(20);
        resultTxtArea.setRows(5);
        jScrollPane1.setViewportView(resultTxtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 53, 190, 220));

        ExitB.setText("Exit");
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });
        jPanel1.add(ExitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 95, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("RESULTS:");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 121, -1));

        resultB.setText("Show results");
        resultB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBActionPerformed(evt);
            }
        });
        jPanel1.add(resultB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_ExitBActionPerformed

    private void resultBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBActionPerformed
        // TODO add your handling code here:
        if (totalScore <= 4) {
            resultTxtArea.setText("mild anxiety" + "/ln");
            //resultTxtArea.setText("Mild anxiety is anxiety that is manageable without any additional techniques. By \"manageable,\" we're not saying that it goes away easily. We're saying that you can still get through your day without panicking, you can enjoy a social life, and you can even find hobbies and activities fun.");
            StateQuiz.addResult("mild Anxiety");
        } else if (totalScore > 5 && totalScore <= 9) {
            resultTxtArea.setText("moderate anxiety");
            // resultTxtArea.setText("Moderate anxiety is the disturbing feeling that some- thing is definitely wrong; the person becomes nervous or agitated. In moderate anxiety, the person can still process information, solve problems, and learn new things with assistance from others.");
            StateQuiz.addResult("moderate Anxiety");
        } else if (totalScore >= 10 && totalScore <= 14) {
            resultTxtArea.setText("moderate severe anxiety");
            //resultTxtArea.setText("people with moderate anxiety may report experiencing symptoms such as feeling on edge, being unable to control their worrying or being unable to relax several days or the majority of days in a week, but not every day");
            StateQuiz.addResult("moderate severe Anxiety");
        } else if (totalScore >= 15 && totalScore <= 21) {
            resultTxtArea.setText("severe anxiety");
            //  resultTxtArea.setText("Panic disorder involves repeated episodes of sudden feelings of intense anxiety and fear or terror that reach a peak within minutes (panic attacks). You may have feelings of impending doom, shortness of breath, chest pain, or a rapid, fluttering or pounding heart (heart palpitations)");
            StateQuiz.addResult("severe Anxiety");
        }


    }//GEN-LAST:event_resultBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionResullts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionResullts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionResullts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionResullts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionResullts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton resultB;
    private javax.swing.JTextArea resultTxtArea;
    // End of variables declaration//GEN-END:variables
}
