/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Kyra Balliram
 */
public class SimonInfo extends javax.swing.JFrame {

    /**
     * Creates new form Home_User
     */
    public SimonInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Instructions = new javax.swing.JScrollPane();
        InstructionOne = new javax.swing.JTextArea();
        OkayOne = new javax.swing.JButton();
        HowToPlay = new javax.swing.JLabel();
        OkayTwo = new javax.swing.JButton();
        ReturnB = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        SimonGIF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstructionOne.setColumns(20);
        InstructionOne.setRows(5);
        InstructionOne.setText("\nPress the 'Go!' button to start the game.\nThis will let Simon have his turn\n (Don't forget to remember which \norder he moves!)\nWhen Simon is done, the text area\nwill tell you it's your turn.\nJust match his moves in the exact order.");
        Instructions.setViewportView(InstructionOne);

        jPanel1.add(Instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 240, 150));

        OkayOne.setText("Okay");
        OkayOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkayOneMouseClicked(evt);
            }
        });
        jPanel1.add(OkayOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 73, -1));

        HowToPlay.setBackground(new java.awt.Color(255, 255, 153));
        HowToPlay.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        HowToPlay.setText("            HOW TO PLAY:");
        jPanel1.add(HowToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 280, 46));

        OkayTwo.setText("Okay");
        OkayTwo.setVisible(false);
        OkayTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkayTwoMouseClicked(evt);
            }
        });
        jPanel1.add(OkayTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 70, -1));

        ReturnB.setText("Return");
        ReturnB.setVisible(false);
        ReturnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBMouseClicked(evt);
            }
        });
        jPanel1.add(ReturnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 70, -1));

        jButton1.setText("Return");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 90, -1));

        SimonGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simon.gif"))); // NOI18N
        SimonGIF.setText("jLabel3");
        jPanel1.add(SimonGIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 630, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void OkayOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkayOneMouseClicked
        // TODO add your handling code here:
        InstructionOne.setText(null);
        InstructionOne.setText("The game will keep track of button presses.\n" +
        "An alert box will pop up \n telling you if you did it correctly or if you lost.\n" +
        "Losing starts the game back at level 1\n" +
        "Matching Simon's moves correctly \n advances you to the next level.");
        OkayOne.setVisible(false);
        OkayTwo.setVisible(true);
    }//GEN-LAST:event_OkayOneMouseClicked

    private void OkayTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkayTwoMouseClicked
        // TODO add your handling code here:
        InstructionOne.setText(null);
        InstructionOne.setText("Don't try to cheat!\n" +
        "If you copy Simon's moves, \n while it is not your turn, \n those clicks won't count.\n" +
        "Note: Be sure to press \n AND release the mouse button \n while over each button.\n" +
        " If you don't,\n the button won't change color \n the way it's supposed to.");
        OkayTwo.setVisible(false);
        ReturnB.setVisible(true);
    }//GEN-LAST:event_OkayTwoMouseClicked

    private void ReturnBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBMouseClicked
        // TODO add your handling code here:
        dispose();
         
    }//GEN-LAST:event_ReturnBMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimonInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimonInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimonInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimonInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimonInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HowToPlay;
    private javax.swing.JTextArea InstructionOne;
    private javax.swing.JScrollPane Instructions;
    private javax.swing.JButton OkayOne;
    private javax.swing.JButton OkayTwo;
    private javax.swing.JToggleButton ReturnB;
    private javax.swing.JLabel SimonGIF;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
