/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Kyra Balliram
 */
import BACKEND.SimonBackend;

import static BACKEND.SimonBackend.waitTimer;
import java.awt.Color;
public class Simon extends javax.swing.JFrame {

    /**
     * Creates new form Simon
     */

    public Simon() {
       initComponents();
            
 
    }
    
     
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redFrame = new javax.swing.JButton();
        blueFrame = new javax.swing.JButton();
        yellowFrame = new javax.swing.JButton();
        greenFrame = new javax.swing.JButton();
        levelTxt = new javax.swing.JLabel();
        ScoreTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(37, 37));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redFrame.setBackground(java.awt.Color.red);
        redFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redFrameMouseClicked(evt);
            }
        });
        getContentPane().add(redFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 120));

        blueFrame.setBackground(java.awt.Color.blue);
        blueFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueFrameMouseClicked(evt);
            }
        });
        getContentPane().add(blueFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 140, 120));

        yellowFrame.setBackground(java.awt.Color.yellow);
        yellowFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowFrameMouseClicked(evt);
            }
        });
        getContentPane().add(yellowFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, 120));

        greenFrame.setBackground(java.awt.Color.green);
        greenFrame.setForeground(java.awt.Color.green);
        greenFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenFrameMouseClicked(evt);
            }
        });
        getContentPane().add(greenFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, 120));

        levelTxt.setText("Level:");
        getContentPane().add(levelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 30));

        ScoreTxt.setText("Score:");
        getContentPane().add(ScoreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 110, 30));

        jLabel3.setText("                        Simons turn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 220, 40));

        jLabel4.setText("Your turn");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 70, 20));

        ReturnButton.setText("Return");
        ReturnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        StartButton.setText("start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        new HomeScreen().setVisible(true);
    }//GEN-LAST:event_ReturnButtonMouseClicked

    
    public static int levelnbr=1;
    public static int i;
    
    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        //sequence of flash
        for (  i=0; i<levelnbr;i++){
        switch(levelnbr){
            case 1: 
                levelTxt.setText("Level:1");
                break;
            case 2:
                levelTxt.setText("Level:2");
                break;
            case 3:
                levelTxt.setText("Level:3");
                break;
            case 4:
                levelTxt.setText("Level:4");
                break;  
        }
        
        if (SimonBackend.chosenButton == SimonBackend.valueRed){
        redFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        redFrame.setBackground(Color.red);
        }else if( SimonBackend.chosenButton==SimonBackend.valueBlue){
        blueFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        blueFrame.setBackground(Color.blue);
        }else if(SimonBackend.chosenButton==SimonBackend.valueYellow){
        yellowFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        yellowFrame.setBackground(Color.yellow);
        }else if (SimonBackend.chosenButton==SimonBackend.valueGreen){
        greenFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        greenFrame.setBackground(Color.green); 
        }
        
        levelnbr++;
         
     }

        

        
    }//GEN-LAST:event_StartButtonActionPerformed

    private void redFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redFrameMouseClicked
        // TODO add your handling code here:
        redFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        redFrame.setBackground(Color.red);  
    }//GEN-LAST:event_redFrameMouseClicked

    private void blueFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueFrameMouseClicked
        // TODO add your handling code here:
        blueFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        blueFrame.setBackground(Color.blue);
    }//GEN-LAST:event_blueFrameMouseClicked

    private void yellowFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowFrameMouseClicked
        // TODO add your handling code here:
        yellowFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        yellowFrame.setBackground(Color.yellow);
        
    }//GEN-LAST:event_yellowFrameMouseClicked

    private void greenFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_greenFrameMouseClicked
        // TODO add your handling code here:
        greenFrame.setBackground(Color.white);
        SimonBackend.waitTimer();
        greenFrame.setBackground(Color.green);
    }//GEN-LAST:event_greenFrameMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simon().setVisible(true);
            }
        });
        
        
        
        
     


    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel ScoreTxt;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton blueFrame;
    private javax.swing.JButton greenFrame;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel levelTxt;
    private javax.swing.JButton redFrame;
    private javax.swing.JButton yellowFrame;
    // End of variables declaration//GEN-END:variables

}
